### ISSUE TITLE
[BUG] Quiet doesn't work.

### ISSUE THREAD

**Issue by NilsIrl** [Sh3llcod3/Memecrypt#1]
Using `cipher.set_quiet()`, doesn't work

**Comment by Sh3llcod3** [comment]
This calls the same method as calling it from the command line does. If it persists, please let me know. 

![quiet](https://user-images.githubusercontent.com/28938427/95004041-0504a080-05de-11eb-8709-b1ea1dd20a24.png)
![quiet2](https://user-images.githubusercontent.com/28938427/95004057-367d6c00-05de-11eb-8cee-ad6836661c7a.png)
